### ISSUE TITLE
Replace "bitcoin"/"namecoin" in code/docs with "xaya"

### ISSUE THREAD

**Issue by DarkClaw1** [xaya/xaya#77]
Throughout the code and docs there are various mentions to bitcoin/namecoin when obviously it should say xaya instead. This seems a bit unprofessional and (naively) should be easily solved.  Is there a reason no tool has been created to automatically substitute these terms?

**Comment by domob1812** [comment]
The problem here is that we regularly merge upstream changes, so we certainly do not want to replace *all* occurances.  We do want to replace everything that is visible to users, but we do not want to replace things that are just variable/function/class names in the code (because doing so would lead to tons more merge conflicts).

If you find any user-visible places that need to be updated (and I'm sure there are some), then feel free to point us to them or submit a pull request.  For places that are purely in code and not visible, we want to stick to the upstream names.

**Comment by DarkClaw1** [comment]
Yea, I was thinking stuff like this:
> The recipient will receive less bitcoins than you enter in the amount field.
https://github.com/xaya/xaya/blob/034e172b3e792b6750b7fc87083537c94e03d3b5/src/wallet/rpcwallet.cpp

**Comment by domob1812** [comment]
With the latest upstream merges, this location is now fixed.  If you have any more concrete places, let us know.  Thanks!
